[package]
name = "flexible_bin_heap"
version = "0.1.0"
authors = ["Kyle Strand <batmanaod@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "*"
quote = "*"

[lib]
proc-macro = true
