[package]
name = "dynamic_ord"
version = "0.1.0"
authors = ["Kyle Strand <kyle.strand@rms.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
